//-----------------------------------------------------------------------------
//  Module: driver
//  Author: PZ
//  Description:
//      UART Driver module — responsible for driving serial input (`sin`) of the
//      DUT based on transactions generated by `tp_gen`.
//
//      The driver fetches UART transactions from `gen2drv_mb` mailbox,
//      serializes them bit-by-bit according to UART protocol timing,
//      and sends them into the DUT. It also handles programming mode (`prog`)
//      and checks the reset behavior of DUT outputs (`sout0`, `sout1`).
//
//  Behavior summary:
//      - Performs DUT reset sequence at startup
//      - Waits for transactions from generator
//      - Sends UART frames (address + data)
//      - Ends when receives `finish_sim` transaction
//
//  Mailboxes used:
//      - gen2drv_mb : source of transactions from generator
//
//  Notes:
//      - UART line idle = logic '1'
//      - Each frame: start(0) + 8 data bits + parity(even) + stop(1)
//      - `reset_dut()` ensures DUT is initialized properly
//-----------------------------------------------------------------------------

module driver (switch_bfm bfm);
    import fifomult_tb_pkg::*;

    //--------------------------------------------------------------------------
    // Main driver process
    //--------------------------------------------------------------------------
    initial begin : drv_blk
        uart_transaction_t tr;

        `ifdef DEBUG
        $display("[%0t] [DRV] Driver started", $time);
        `endif

        // UART line idle high (default)
        bfm.sin = 1'b1;

        // Perform two resets to ensure stable DUT outputs
        bfm.reset_dut();
        bfm.reset_dut();

        // Basic post-reset check — outputs must be idle high
        assert (bfm.sout0 == 1'b1 && bfm.sout1 == 1'b1)
            else begin
                `ifdef DEBUG
                $display("[%0t] [DRV] sout0 or sout1 not 1'b1 after reset", $time);
                `endif
                bfm.test_result = TEST_FAILED;
            end

        //--------------------------------------------------------------------------
        // Main driver loop
        //--------------------------------------------------------------------------
        forever begin
            // Wait for a transaction from the generator
            bfm.gen2drv_mb.get(tr);

            // Stop condition (end of simulation)
            if (tr.finish_sim) begin
                `ifdef DEBUG
                $display("[%0t] [DRV] Finish_sim received — driver exiting", $time);
                `endif
                break;
            end

            // Print debug info
            `ifdef DEBUG
            $display("[%0t] [DRV] Sending packet addr=0x%02h data=0x%02h, port=%0d prog=%0b",
                    $time, tr.switch_packet.addr.data, tr.switch_packet.data.data, tr.port, tr.prog);
            `endif

            // Drive DUT
            bfm.prog = tr.prog;
            bfm.uart_send_frame(tr.switch_packet.addr, bfm.sin);  // Send address frame
            bfm.uart_send_frame(tr.switch_packet.data, bfm.sin);    // Send data frame
            bfm.prog = 0;                                           // Disable programming after packet
        end

        //--------------------------------------------------------------------------
        // Simulation finished
        //--------------------------------------------------------------------------
        `ifdef DEBUG
        $display("[%0t] [DRV] Driver finished", $time);
        `endif
    end


    

endmodule : driver
